# Generated by Django 3.1.7 on 2021-04-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(verbose_name='Айдишник сессии')),
                ('session_turn', models.IntegerField(verbose_name='Номер хода')),
                ('session_phase', models.CharField(max_length=125, verbose_name='Статус хода')),
                ('turn_count', models.IntegerField(verbose_name='Количество ходов')),
            ],
        ),
    ]
